### ISSUE TITLE
Corrections and suggestions for the font

### ISSUE THREAD

**Issue by AlsoScratch** [cssobral2013/Argentum-Sans#1]
First of all, thank you for the beautiful font. I do think it will be useful for a lot of situations. That being said, there are still a few mistakes in the font and I think it can definitely do with some other improvements as well.

**Corrections:**
- `ḷ` (u+1e37) in the Regular weight does not have a bend to the right. Please check if there are any other precomposed characters in all weights that do not appear correctly.

- Diacritics in Ȱ (u+0230) is not centered, it's a bit to the right. (all non-italic)

- I noticed the inconsistency in the width of the stroke between `Ŧ` and `ŧ`:
![Annotation 2019-12-06 121621](https://user-images.githubusercontent.com/48752273/70295519-4c859900-1822-11ea-9531-2a6caae2a638.png)

I soon figured out that the lower horizontal line in `ŧ` was just a copy of the upper one. By right, the lower line should be thinner and slightly shorter. (See `Đđ`, `Ħħ`, `Ŧ`; those appear correct)

**Optimizations:**
This is where the font is overall correct, but there are still clear areas for improvement.
- At 11 pt the dot of the `i` (in the Regular and Medium weights at least) appears to merge with the body:
![Annotation 2019-12-06 120009](https://user-images.githubusercontent.com/48752273/70294875-fb74a580-181f-11ea-956c-00c9fe4e017d.png)

- On a similar note, in the Windows Character map, the breve and tilde diacritics over some letters diacritics appear reduced to a line:
![Annotation 2019-12-06 115642](https://user-images.githubusercontent.com/48752273/70294799-a33da380-181f-11ea-9aa1-50a7ac12de5d.png)
I would also like to request that the plus and minus signs look more consistent in the Character Map:
![Annotation 2019-12-06 122230](https://user-images.githubusercontent.com/48752273/70295758-1a286b80-1823-11ea-8b1f-b6b23f7977a2.png)

- This one is regarding the Font Library page, notice how the h's, m's and n's have their arches a bit too low:
![Annotation 2019-12-06 143857](https://user-images.githubusercontent.com/48752273/70301794-52857500-1836-11ea-92c8-247611efbca0.png)

Now for the suggestions.

**Character suggestions:**
- Complete u+1e00 through u+1e95
- Ǟ (u+01de) and ǟ (u+01df)
- Ȯ (u+022E) and ȯ (u+022F)
- Ǵ (u+01f4) and ǵ (u+01f5)

**OpenType suggestions**
- Selector for proportional figures
- Selector for capital `I` with bars
- Selector for slashed zero

Please notify me of any updates. Thanks!

**Comment by cssobral2013** [comment]
@AlsoScratch, Regarding serifed 'I', I think I'll have to go to Montserrat sources.

**Comment by cssobral2013** [comment]
@AlsoScratch, the glitch in tbar in fact happens in all weights except Thin and Thin Italic.

**Comment by AlsoScratch** [comment]
> @AlsoScratch, Regarding serifed 'I', I think I'll have to go to Montserrat sources.

That's okay. I suggest you work on the corrections first, the OpenType suggestions can come later.

**Comment by AlsoScratch** [comment]
I'm curious to know, are you working on the full u+1e00 through u+1e95?

**Comment by AlsoScratch** [comment]
Is the full u+1e00 through u+1e95 going to be added?

**Comment by cssobral2013** [comment]
@AlsoScratch, I'm just making the full charset from 1e00 to 1e9b.

**Comment by cssobral2013** [comment]
Regarding proportional figures - I don't want them, 'cause this font is designed to be with tabular 0-9 numerals.

**Comment by cssobral2013** [comment]
Most of these issues are solved with 2.6 update. If you find new issues, feel free to open a new issue.
