### ISSUE TITLE
What's up with the new '1' design?

### ISSUE THREAD

**Issue by AlsoScratch** [cssobral2013/Argentum-Sans#11]
The variant looks appropriate for tabular/&#x200b;proportional figures but you said you wouldn't implement those.

**Comment by AlsoScratch** [comment]
What I'm trying to say is that the previous design of the '1' works well for proportional figures.

**Comment by cssobral2013** [comment]
@AlsoScratch, what I said before is that I just don't want to implement
proportional figures.

Em qui, 20 de fev de 2020 1:14 PM, AlsoScratch <notifications@github.com>
escreveu:

**Comment by AlsoScratch** [comment]
I wish to know why the design of the '1' was changed.

**Comment by cssobral2013** [comment]
This was made to reduce whitespace and to make more clear the 1 is tabular.
Em qui, 20 de fev de 2020 11:19 PM, AlsoScratch <notifications@github.com>
escreveu:
