### ISSUE TITLE
Issue with some glyphs

### ISSUE THREAD

**Issue by maa7** [cssobral2013/Argentum-Sans#15]
Hello,
Weird things with Cyrillic:
![image1](https://github.com/cssobral2013/Argentum-Sans/assets/45234995/01a735cc-3258-4a58-bf4b-9553fbc1c567)

**Comment by cssobral2013** [comment]
Fixed in version 3.17.

**Comment by maa7** [comment]
![Image2](https://github.com/cssobral2013/Argentum-Sans/assets/45234995/6138ea95-abe0-4146-b515-f76b2056a6e4)
![image3](https://github.com/cssobral2013/Argentum-Sans/assets/45234995/cce51071-55a5-4b22-9a52-b5e113c7123e)

**Comment by cssobral2013** [comment]
Fixed in version 3.17(2).
