### ISSUE TITLE
Kerning issues (Extra Light weight)

### ISSUE THREAD

**Issue by AlsoScratch** [cssobral2013/Argentum-Sans#2]
![Annotation 2019-12-12 140332](https://user-images.githubusercontent.com/48752273/70687281-a9cd8e80-1ce9-11ea-973b-d5cb8de49af6.png)
![Annotation 2019-12-12 141957](https://user-images.githubusercontent.com/48752273/70687991-a3401680-1ceb-11ea-8e81-0b9ca6a58753.png)

I didn't try to highlight _every_ kerning issue in here, but I did try to highlight every letter that had issues. (I only noticed it in the Extra Light weight.)

**Comment by cssobral2013** [comment]
Solved in the latest commit of today (Dec 12, 2019). I had to re-edit the ExtraLight weight. But it is solved now.
