### ISSUE TITLE
(HTML demo) Black Italic header is missing the 'Italic'

### ISSUE THREAD

**Issue by AlsoScratch** [cssobral2013/Argentum-Sans#4]
<img width="991" alt="Screenshot 2019-12-14 at 10 34 13 AM" src="https://user-images.githubusercontent.com/48752273/70842336-4cf2e500-1e5d-11ea-9e9f-b4eb5c5d53e9.png">

**Comment by cssobral2013** [comment]
HTML preview was just updated now.
