### ISSUE TITLE
Inconsistent macron diacritics

### ISSUE THREAD

**Issue by AlsoScratch** [cssobral2013/Argentum-Sans#5]
<img width="629" alt="Screenshot 2019-12-23 at 3 12 10 AM" src="https://user-images.githubusercontent.com/48752273/71326189-69181580-2532-11ea-80e1-76861d33afd2.png">

This was originally going to be about how the macron diacritic in `ǟ` is too high compared to `ȫ`. But now I found that some characters with this diacritic have it longer (see `Ō`) than others. (see `Ȫ`)
In my opinion, the longer macron appears to be correct and the macron and umlaut in `Ǟ` are properly positioned.

**Comment by AlsoScratch** [comment]
Just found out that even the `Ō` macron is slightly longer than the `ō` macron. Now I don't know which one is correct, definitely not the teeny one in `ȫ`.

**Comment by cssobral2013** [comment]
Although Argentum Sans is good, it inherited many bugs from upstream, it'll
take very long to correct these.

Em sex, 27 de dez de 2019 6:33 AM, AlsoScratch <notifications@github.com>
escreveu:

**Comment by AlsoScratch** [comment]
How long do you expect it to take?

**Comment by cssobral2013** [comment]
A month or more. This is because I need to review the other issues you
opened. Another point is that Argentum Sans inherited bugs from upstream,
as I said earlier.

Em sex, 27 de dez de 2019 1:55 PM, AlsoScratch <notifications@github.com>
escreveu:

**Comment by AlsoScratch** [comment]
Within a month would be great!

**Comment by cssobral2013** [comment]
The uneven macrons are correct. This is because, as of upstream, the uppercase macron and lowercase macron are designed to be different.

**Comment by AlsoScratch** [comment]
The height of the macron between `ǟ` and `ȫ` should be consistent at least.

**Comment by cssobral2013** [comment]
Solved with 2.6 update.
